name: appsonair_flutter_sdk
description: AppsOnAir flutter sdk enables you to configure the version update of your app directly through AppsOnAir.
version: 0.2.2 
# homepage:
repository: https://github.com/apps-on-air/AppsOnAir-Flutter-SDK

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  
  plugin:
    platforms:
      android:
        package: com.lwpackage.applicationupdate.flutter_app_update_package
        pluginClass: FlutterAppUpdatePackagePlugin
      ios:
        pluginClass: FlutterAppUpdatePackagePlugin